### ISSUE TITLE
integration with moment-timezone

### ISSUE THREAD

**Issue by marcelofpalves** [reasonml-community/bs-moment#11]
This is not really an issue with this package but...

The `moment-timezone` library adds a `.tz` function to the `moment` prototype.
https://github.com/moment/moment-timezone/

How I express this external and still use this package?

Thank you!

**Comment by chenglou** [comment]
Would [this](https://reasonml.github.io/try/?reason=LYewJgrgNgpgBAWRMGA7ALnAvHA3ugTwAd50BuAXzIChqYAPdGAJ1QEMo50AvALkWRp0AOkxYAfHADO6ZgEtUAc2ySkKDKOxwARD21wA2gAEjAIynCpaMAF0a1WJjZSw-NUM04DAUnPDmbADuOkTMMEyoYAAqABZyUgCSUgCC7hgJqDJsqADGMNp2tI5wYVLQYlzccM5gOsko8jlsAPQAMiBSAPrJSjCwUto0QA) work?

**Comment by marcelofpalves** [comment]
Thanks! The output is now correct except it doesn't import "moment-timezone".
I want to express "import this module as a side-effect don't give it a name or anything"

```js
import moment from 'moment'
import 'moment-timezone'
```

**Comment by chenglou** [comment]
Solved in Discord through `[%%bs.raw "require('moment-timezone)"]`

Though we should just wrap it with our own idiomatic API because these kind of APIs are pretty darn imperative side-effectful.
