### ISSUE TITLE
Add moment.js to peerDependencies

### ISSUE THREAD

**Issue by jchavarri** [reasonml-community/bs-moment#18]
~~Really minor :) for consumers to get the original `moment` package when downloading the bindings and avoid version mismatches, it should be better moved to `dependencies` (now it's [in `devDependencies`](https://github.com/reasonml-community/bs-moment/blob/master/package.json#L22)).~~ Edit: better add it to `peerDeps`, see below 👇

**Comment by Jimexist** [comment]
> for consumers to get the original moment package when downloading

i think the users should try to add `moment` in their own `package.json`

> avoid version mismatches

a better solution is to include `moment` in peer dependencies. but for dev dependencies it's for the sake of developing in this repo.

**Comment by jchavarri** [comment]
Interesting. I guess I was thinking on cases where you start a project from scratch, but `peerDependencies` definitely makes more sense for JavaScript projects that already exists, and are progressively migrated to Reason / OCaml, as there are instances of `moment.js` objects being passed around. [This article](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/) helped me understand better when to use `peerDependencies`, depending if abstract types are being accepted or returned from the public interface contract.

It seems other projects in a similar situation like `grunt-contrib-clean` also have [`devDependencies`](https://github.com/gruntjs/grunt-contrib-clean/blob/master/package.json#L24) and [`peerDependencies`](https://github.com/gruntjs/grunt-contrib-clean/blob/master/package.json#L30) ([relevant issue](https://github.com/gruntjs/grunt-contrib-clean/issues/67))

**Comment by Jimexist** [comment]
@jchavarri FYI this is now added
