### ISSUE TITLE
can't load / resolve moment 

### ISSUE THREAD

**Issue by jcleefw** [reasonml-community/bs-moment#27]
Hi there, i'm fairly new to reason.   i am trying to load bs-moment in to my project.

`Module not found: Error: Can't resolve 'moment'` 

The generated bs.js has `var Moment = require("moment");`
 
Is this correct? is this suppose to be loading `bs-moment` since node_module package is actually bs-moment?

**Comment by jcleefw** [comment]
think i've got it. It's just a missing step in installing moment. Will open a PR to have clearer instructions.

**Comment by Jimexist** [comment]
@jcleefw i think you are supposed to install `moment` itself
