### ISSUE TITLE
Release newest code

### ISSUE THREAD

**Issue by kamilkuz** [reasonml-community/bs-moment#34]
Hello,

I use bs-moment in my project. I install it using npm: https://www.npmjs.com/package/bs-moment
And while building i have two warnings about unused method setYear and setMonth.
I checked this in repository and in master branch this bug was fixed, but in npm the newest version is without this fix.
I'm quite new in github and i don't know how publishing to npm works, but it will be great if in npm package will be newest code, without this annoying warnings.

**Comment by Jimexist** [comment]
@kamilkuz new code released, please see https://www.npmjs.com/package/bs-moment

**Comment by kamilkuz** [comment]
I checked it and is ok. Thanks
