### ISSUE TITLE
API feedback from concrete usage example

### ISSUE THREAD

**Issue by glennsl** [reasonml-community/bs-moment#7]
```reason
open MomentRe;

 let () =
    "March 7 2009 7:30pm EST"
    |> Js.String.replace "EST" "-0500"
    |> (fun s => momentWithFormat s "MMMM D YYYY h:mma Z")
    |> Moment.add duration::(duration 12 `hours)
    |> Moment.defaultFormat
    |> Js.log
```

I wanted to make a date manipulation example for the bucklescript cookbook, but I think the API currently leaves a bit to desire. I realize most of this is from trying to model it very closely to the js API, but just to get this on the record. The issues I have with it are:

1. `momentWithFormat` is a bit of a non-sensical name
2. `momentWithFormat` is not in pipe form, so I have to use a lambda function to fit it into the pipeline
3. `momentWithFormat`s arguments aren't labelled, and so very easy to mix up. Doubly so since it's not in pipe form either (I wasted a ton of time on this, trying to figure out why the date passed in was considered invalid...)
4. I still find it inconsistent to not have the `moment...` functions in the `Moment` module (We've talked about this before though)
5. `Moment.add`s `duration` argument label seems redundant
6. `defaultFormat` is not a verb, like most other function names
7. `defaultFormat` is also an actual property in `moment.js`, which is a bit confusing.

**Comment by Jimexist** [comment]
@glennsl thanks for the great feedback, glad that you actually put it into real use cases

- for the lack of a better name I used `momentWithFormat`, but i'm totally open to better alternatives
- same with `defaultFormat`: i didn't notice before.

I think I can make changes on both of seem soon by the end of this week. On `4.` and `5.` let's revisit after the change.

**Comment by Jimexist** [comment]
https://github.com/BuckleTypes/bs-moment/issues/4

**Comment by glennsl** [comment]
Internally the `moment` constructor is called `createLocal`, but I'd use different names depending on the variant. `monent()` can be `now` (or `make`, but that's less specific), `moment('Jul 7 2017')` can be `parse`, and its variants `parseWithFormat` etc., and the other construction forms can be `fromObject`, `fromDate`, `fromUnixTime`, `fromArray` and `clone`.

`defaultFormat` could just be `formatDefault`
